<?php
const CARD_TYPE_MONSTER = 9;
const CARD_TYPE_NORMAL = 1;
const CARD_TYPE_EFFECT = 7;
const CARD_TYPE_PENDULUM = 8;
const CARD_TYPE_FUSION = 4;
const CARD_TYPE_REVENGE = 6;
const CARD_TYPE_SPELL = 2;
const CARD_TYPE_TRAP = 3;
const CARD_TYPE_NORMAL_TRAP = 10;
const CARD_TYPE_RITUAL = 5;
